---
title: "503Final"
author: "Hong Xu"
date: "November 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
GT <- read.csv("./data/globalterrorismdb_0718dist.csv")

GT[GT==""] <- NA #replace empty cells with NA

```


```{r}
library(ggplot2)
library(grid)
library(leaflet)
library(dplyr)
```

```{r}
mapIND <- leaflet() %>% 
  addTiles('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
  attribution='Map tiles by 
    <a href="http://stamen.com">Stamen Design</a>, 
    <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> 
    &mdash; Map data &copy; 
    <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>') %>%
  setView(80, 24, zoom= 5)

```


```{r}
ggplot(GT, aes(x = iyear))+ labs(title =" Terrorist attacks globally between 1970-2017 by attack type", x = "Years", y = "Number of Attacks", size = 15) + 
  geom_bar(colour = "grey19", fill = "tomato3") + facet_wrap(~attacktype1_txt, ncol = 3) + 
  theme(axis.text.x = element_text(hjust = 0.5, size = 10)) + theme(strip.text = element_text(size = 8, face = "bold"))

ggsave("types.jpg", plot = last_plot())
```

```{r}
ggplot(data=GT, aes(x=iyear,fill=General_region)) + geom_bar() + ggtitle("Yearly Terrorist Attacks by Region")+         
    labs(x = "Years", y = "Number of Attacks")+ scale_fill_discrete(name = "Region")+scale_fill_manual(values=c('dodgerblue4','darkgoldenrod3','blue', 'deeppink4','green','darkorchid3'))


ggsave(plot = last_plot(), "Bar.jpg")
```

```{r}
GT %>% filter(targtype1_txt != "") %>% group_by(targtype1_txt) %>% summarise(nt = length(targtype1_txt)) %>% ungroup() -> dft
ggplot(data = dft, aes(x = reorder(targtype1_txt,nt), y = nt)) +  
  geom_bar(stat="identity", fill="gold", colour="black") +
  coord_flip() + theme_bw(base_size = 8)  +
   labs(title="Number of Attacks to each Target Types ", x ="Target type", y = "Number of events")
ggsave("ggpairs.jpg", last_plot(), dpi=500)

```





